"""
Django settings for cs_cloud project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k+8cd@$_6$0!jijt67co&^05dc7$-2cpl13cxwg6qygno6^ysg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Add allowed hosts in production
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'cloud',
	'mathfilters',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cs_cloud.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'cs_cloud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# SESSION AGE 30 Minutes
# User automatically logged out after 30 minutes of inactivity
# Or if they close their browser
SESSION_COOKIE_AGE = 30 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg' # UTC+2

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'cloud.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
	os.path.join(BASE_DIR, "static"),
)

# Absolute filesystem path to the directory that will hold user-uploaded files.
# where all user data will be stored
# May be changed to alternative location for more storage
MEDIA_ROOT = os.path.join(BASE_DIR, "data")
TRASH_ROOT = os.path.join(BASE_DIR, "trash")


"""
Default disk quota assigned to each new user
Units: Bytes (Base 2 - 1 kiB = 1024 bytes)
Default: 100 MiB
Note: Make migrations when updating value
"""
DEFAULT_QUOTA = 104857600

"""
How long the 'Change Password' URL should be
valid, in days.
Current: 1 day (24 Hours)
"""
PASSWORD_RESET_TIMEOUT_DAYS = 1

"""
External server url
TODO: CHANGE IN PRODUCTION
"""
#EXTERNAL_URL = 'http://cloud.cs.up.ac.za/'
EXTERNAL_URL = 'http://127.0.0.1:8000/'

"""
Email settings
TODO: CHANGE IN PRODUCTION
Note: nigelvm.com used for demonstration purposes only
"""
FROM_EMAIL_ADDRESS = 'CS Cloud <cs_cloud@nigelvm.com>'
EMAIL_USE_TLS = True
EMAIL_HOST = "nigelvm.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "cs_cloud"
EMAIL_HOST_PASSWORD = "cloud.cs.up.ac.za"