# Generated by Django 2.2.1 on 2019-06-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_group_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicShare',
            fields=[
                ('url', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(default='', max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
