# Generated by Django 2.2.1 on 2019-07-18 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_group_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareUrl',
            fields=[
                ('url', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=256)),
                ('can_edit', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepient', to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uurl', to='cloud.ShareUrl')),
            ],
        ),
        migrations.CreateModel(
            name='PublicShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=256)),
                ('can_edit', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purl', to='cloud.ShareUrl')),
            ],
        ),
        migrations.CreateModel(
            name='GroupShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=256)),
                ('can_edit', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gurl', to='cloud.ShareUrl')),
            ],
        ),
    ]
